apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  namespace: {{.Release.Namespace}}
  labels:
    demo: app1
spec:
  type: ClusterIP
  selector:
    demo: app1
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
